[build]
  command   = "npm --prefix frontend ci && npm --prefix frontend run build"
  publish   = "frontend/dist"
  functions = "netlify/functions"

[dev]
  command = "npm --prefix frontend run dev"
  port = 8888
  targetPort = 5173

# Redireccionamiento para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
